version: "3.5"
services:
  api01: &api
    image: marcelocortess/rinha:0.0.1-SNAPSHOT
    hostname: api01
    networks:
      - default
    ports:
      - "8081:8080"
    environment:
      - DB_HOSTNAME=db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rinhabackend
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=driven
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "190MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rinhabackend
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=driven    
    ports:
      - "8082:8080"

  db:
    image: postgres:alpine
    hostname: db
    networks:
      - default
    environment:
      POSTGRES_DB: rinhabackend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: driven
    ports:
      - "5433:5432" 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: "160MB"

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      -  ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '10MB'

networks:
  default:
    driver: bridge
    name: rinha-network